name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    if: github.repository == 'procaktomasz/LibrusSynergiaHA'
    runs-on: "ubuntu-latest"
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
